version: "3.9"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    init: true
    image: wurstmeister/zookeeper
    ports:
      - ${ZOOKEEPER_PORT_EXT}:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  kafka:
#    hostname: kafka
#    container_name: kafka
#    init: true
#    image:  docker.io/bitnami/kafka:3.7
#    # depends_on:
#    #   - zookeeper
#    ports:
#      - ${KAFKA_PORT_EXT}:49092
#      # - 9093:9093
#      # - 49092:49092
#    environment:
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CFG_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://0.0.0.0:49092
#      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://172.17.32.1:49092
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  kafka:
    hostname: kafka
    container_name: kafka
    image: docker.io/bitnami/kafka:3.7
    ports:
      - ${KAFKA_PORT_EXT}:49092
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL_SAME_HOST://0.0.0.0:49092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://${KAFKA_IP}:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on:
      - zookeeper