version: "3.9"
services:
  etl:
    init: true
    restart: always
    hostname: etl
    build: ./etl
    container_name: etl
    expose:
      - "${DRACO_PORT_EXT}"
    ports:
      - "${DRACO_PORT_EXT}:${DRACO_PORT_EXT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://${DRACO_IP}:${DRACO_PORT_EXT}
      interval: 5s
      timeout: 10s

  writetomongo:
    init: true
    restart: always
    hostname: writetomongo
    build:
      context: ./devices
      dockerfile: writetomongo.Dockerfile
    container_name: writetomongo
    networks:
      - default
    env_file:
      - .env
    depends_on:
      mongo-db:
        condition: service_healthy

