version: "3.9"
services:
  etl:
    init: true
    restart: always
    hostname: etl
    container_name: etl
    build: ./etl
    ports:
      - "${DRACO_PORT_EXT}:${DRACO_PORT_EXT}"
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://${DRACO_IP}:${DRACO_PORT_EXT}
      interval: 5s
      timeout: 10s

  writetomongo:
    init: true
    restart: always
    hostname: writetomongo
    container_name: writetomongo
    build:
      context: ./devices
      dockerfile: writetomongo.Dockerfile
    env_file:
      - .env

