version: "3.9"
services:
  fiware2kafka:
    init: true
    image: w4bo/fiware2kafka:1.0.11
    environment:
      # Kafka
      - KAFKA_IP=kafka
      - KAFKA_PORT_EXT=9092
      # FIWARE2KAFKA variables
      - FIWARE2KAFKA_IP=fiware2kafka
      - FIWARE2KAFKA_PORT_EXT=5050
      - RAW_TOPIC=raw
      # FIWARE
      - ORION_IP=orion
      - ORION_PORT_EXT=1026
    deploy:
      placement:
        constraints:
          - node.role != manager 
    networks:
      - BIG-dataplatform-network

  kafka2mongo:
    init: true
    image: w4bo/kafka2mongo:1.0.11
    environment:
      # Persistence
      - MONGO_DB_PERS_IP=mongodb
      - MONGO_DB_PERS_PORT_EXT=27017
      - MONGO_DB_PERS_DB=persistence
      # KAFKA
      - KAFKA_IP=kafka
      - KAFKA_PORT_EXT=9092
      # FIWARE2KAFKA variables
      - RAW_TOPIC=raw
      # Image server (required to change the URLs of images)
      - IMAGESERVER_IP=192.168.30.102
      - IMAGESERVER_PORT_HTTP_EXT=49080
    deploy:
      placement:
        constraints:
          - node.role != manager 
    networks:
      - BIG-dataplatform-network

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
