version: "3.9"
services:
  fiware2kafka:
    init: true
    restart: always
    hostname: fiware2kafka
    container_name: fiware2kafka
    build: ./fiware2kafka
    ports:
      - "${FIWARE2KAFKA_PORT_EXT}:${FIWARE2KAFKA_PORT_EXT}"
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://${FIWARE2KAFKA_IP}:${FIWARE2KAFKA_PORT_EXT}
      interval: 5s
      timeout: 10s

  kafka2mongo:
    init: true
    restart: always
    hostname: kafka2mongo
    container_name: kafka2mongo
    build:
      context: ./kafka2mongo
      dockerfile: kafka2mongo.Dockerfile
    env_file:
      - .env

