name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Launch and test
        run: |
          cd dataplatform-core
          chmod +x *.sh
          chmod +x scripts/*.sh
          chmod +x kafka2mongo/gradlew
          for i in $(seq 1)
          do
            echo "Run $i"
            scripts/config.sh
            ./launch.sh -t
            ./stop.sh
          done
      - name: Set up a swarm with a single node and create the docker network
        run: |
          docker swarm init
          docker network create --driver overlay BIG-dataplatform-network
      - name: Check the deploy of the swarm
        run: |
          cd dataplatform-core
          docker stack deploy --compose-file docker-stack.yml FIWARE-ext
  release:
    needs:
      - build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Release
        run: |
          npm install
          npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Log in to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Retrieve version
        id: tag  
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for fiware2kafka
        id: meta1
        uses: docker/metadata-action@75359341f62c2d990e0aa8543e545c74eec643ff
        with:
          images: ${{ secrets.DOCKER_IMAGENAME1 }}
          tags: |
            ${{steps.tag.outputs.version}}
            latest
      - name: Build and push fiware2kafka image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: ./dataplatform-core/fiware2kafka
          # file: ./Dockerfile
          push: true
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}
      - name: Extract metadata (tags, labels) for kafka2mongo
        id: meta2
        uses: docker/metadata-action@75359341f62c2d990e0aa8543e545c74eec643ff
        with:
          images: ${{ secrets.DOCKER_IMAGENAME2 }}
          tags: |
            ${{steps.tag.outputs.version}}
            latest
      - name: Build and push kafka2mongo image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: ./dataplatform-core/kafka2mongo
          # file: ./Dockerfile
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
